import { Link } from "react-router-dom";
import Header from "../components/Header";
import Footer from "../components/Footer";
import { useCart } from "../components/CartContext";

export default function Cart() {
  const { items, subtotal, shipping, total, updateQty, removeFromCart } = useCart();
  return <div className="page cart-page"><Header /><nav className="breadcrumb"><Link to="/">Home</Link><span>/</span><span>Your bag</span></nav><main className="cart-section"><h1>Your bag</h1>{items.length === 0 ? <div className="cart-empty"><h2>Your bag is empty</h2><p>Choose a few favorite pieces and come back here when you are ready.</p><Link to="/products">Continue shopping</Link></div> : <div className="cart-container"><div className="cart-items">{items.map(({ product, qty }) => <div className="cart-item" key={product.id}><div className="cart-item-image"><img src={product.image} alt={product.name} /></div><div className="cart-item-info"><p>{product.category}</p><h3>{product.name}</h3><Link to={`/products?id=${product.id}`}>View details</Link></div><div className="cart-item-qty"><button onClick={() => updateQty(product.id, qty - 1)} aria-label="Decrease quantity">−</button><input value={qty} onChange={(e) => updateQty(product.id, Number(e.target.value) || 0)} /><button onClick={() => updateQty(product.id, qty + 1)} aria-label="Increase quantity">+</button></div><div className="cart-item-total"><strong>${(product.price * qty).toFixed(2)}</strong><button onClick={() => removeFromCart(product.id)}>Remove</button></div></div>)}</div><aside className="cart-summary"><h2>Order summary</h2><div className="cart-summary-row"><span>Subtotal</span><span>${subtotal.toFixed(2)}</span></div><div className="cart-summary-row"><span>Shipping</span><span>{shipping ? `$${shipping.toFixed(2)}` : "Complimentary"}</span></div><div className="cart-summary-row total"><span>Total</span><span>${total.toFixed(2)}</span></div><button className="checkout-btn" onClick={() => alert("Demo checkout: connect your checkout resource here.")}>Proceed to checkout</button><Link to="/products" className="continue-shopping">← Continue shopping</Link></aside></div>}</main><Footer /></div>;
}
